AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Vpc
        Parameters:
          - VpcName
          - VpcCidrBlock
      - Label:
          default: VS Code on EC2 Instance
        Parameters:
          - AmiId
          - InstanceType

Parameters:
  VpcName:
    Description: Name for the VPC to Create
    Type: String
    Default: vsc-vpc
    AllowedPattern: ".+"
    ConstraintDescription: "Parameter [VpcName] must not be empty"
  VpcCidrBlock:
    Description: CIDR Block for the VPC to Create (ex 10.0.0.0/16)
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: '(([1-9]{0,1}[0-9]{0,2}|2[0-4][0-9]|25[0-5])\.){3}([1-9]{0,1}[0-9]{0,2}|2[0-4][0-9]|25[0-5])\/([1-2][0-9]|3[0-1])'
    ConstraintDescription: "Parameter [VpcCidrBlock] is invalid"
  AmiId:
    Description: EC2 AMI Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"
    AllowedValues:
      # aws ssm get-parameters-by-path --path /aws/service/ami-amazon-linux-latest --query 'Parameters[].Name'
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-6.1-arm64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-6.1-x86_64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-arm64"
      - "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2"
      - "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-s3"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-ebs"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
      - "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64"
      - "/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-ebs"
      - "/aws/service/ami-amazon-linux-latest/amzn-ami-minimal-hvm-x86_64-ebs"
      - "/aws/service/ami-amazon-linux-latest/amzn-ami-minimal-hvm-x86_64-s3"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-arm64-gp2"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs"
      - "/aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-x86_64-ebs"
    AllowedPattern: ".+"
    ConstraintDescription: "Parameter [AmiId] must not be empty"
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t1.micro
      - t2.2xlarge
      - t2.large
      - t2.medium
      - t2.micro
      - t2.nano
      - t2.small
      - t2.xlarge
      - t3.2xlarge
      - t3.large
      - t3.medium
      - t3.micro
      - t3.nano
      - t3.small
      - t3.xlarge
      - t3a.2xlarge
      - t3a.large
      - t3a.medium
      - t3a.micro
      - t3a.nano
      - t3a.small
      - t3a.xlarge
      - t4g.2xlarge
      - t4g.large
      - t4g.medium
      - t4g.micro
      - t4g.nano
      - t4g.small
      - t4g.xlarge
    AllowedPattern: ".+"
    ConstraintDescription: "Parameter [InstanceType] must not be empty"

Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub
        - "key-${Id}"
        - Id: !Select [3, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
  
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsHostnames: True
      CidrBlock: !Ref VpcCidrBlock
      Tags: 
        - Key : Name
          Value : !Ref VpcName
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: !Select [0, !Cidr [ !GetAtt Vpc.CidrBlock, 16, 8 ]]
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: !Sub "${VpcName}-subnet-public1-${AWS::Region}a"
        - Key: kubernetes.io/role/elb
          Value: 1
      VpcId: !Ref Vpc
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${VpcName}-igw"
  VpcInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc
  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key : Name
          Value : !Sub "${VpcName}-rtb-public"
      VpcId: !Ref Vpc
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTable
      SubnetId: !Ref PublicSubnet
  PublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicSubnetRouteTable

  OpsEc2:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Count: '1'                
        Timeout: PT10M
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      NetworkInterfaces: 
        - AssociatePublicIpAddress: True
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet: 
            - !Ref OpsEc2SecurityGroup
      Tags: 
        - Key: Name
          Value: vscode
      IamInstanceProfile: !Ref OpsEc2InstanceProfile
      UserData: 
        # sudo tail -f /var/log/cloud-init-output.log
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            dnf update -y
            dnf install -y git
            dnf groupinstall -y "Development Tools"
            dnf install -y python3.12
            python3.12 -m ensurepip --upgrade
            python3.12 -m pip install --upgrade pip
            ln -s /usr/bin/pip3.12 /usr/local/bin/pip
            ln -s /usr/bin/python3.12 /usr/bin/python
            wget https://github.com/coder/code-server/releases/download/v4.93.1/code-server-4.93.1-linux-amd64.tar.gz
            tar -xzf code-server-4.93.1-linux-amd64.tar.gz
            mv code-server-4.93.1-linux-amd64 /usr/local/lib/code-server
            ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code-server
            mkdir -p /home/ec2-user/.config/code-server
            cat <<EOF > /home/ec2-user/.config/code-server/config.yaml
            bind-addr: 0.0.0.0:8000
            auth: none
            cert: false
            EOF
            chown -R ec2-user:ec2-user /home/ec2-user/.config
            cat <<EOF > /etc/systemd/system/code-server.service
            [Unit]
            Description=VS Code Server
            After=network.target
            [Service]
            Type=simple
            User=ec2-user
            ExecStart=/usr/local/bin/code-server --config /home/ec2-user/.config/code-server/config.yaml /home/ec2-user
            Restart=always
            [Install]
            WantedBy=multi-user.target
            EOF
            systemctl daemon-reload
            systemctl enable code-server
            systemctl start code-server

            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource OpsEc2 --region ${AWS::Region}

            su - ec2-user <<'EOF'
            git clone https://github.com/iamhansko/eks-quickstart.git
            mv eks-quickstart /home/ec2-user/scripts
            chmod +x /home/ec2-user/scripts/*

            mkdir -p /home/ec2-user/bin
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /home/ec2-user/bin/kubectl
            export PATH=/home/ec2-user/bin:$PATH
            echo "export PATH=/home/ec2-user/bin:$PATH" >> ~/.bashrc
            echo "alias k=kubectl" >>~/.bashrc
            echo "complete -o default -F __start_kubectl k" >>~/.bashrc
            echo "source <(kubectl completion bash)" >>~/.bashrc

            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            aws configure set region ${AWS::Region}
            
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > /home/ec2-user/get_helm.sh
            chmod 700 /home/ec2-user/get_helm.sh
            /home/ec2-user/get_helm.sh
            EOF
  OpsEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Ops EC2 SSH Connection"
      GroupName: ops-ec2-sg
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: ops-ec2-sg
  OpsEc2IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  OpsEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
        - !Ref OpsEc2IamRole